blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/claylo/scrat/discussions
    about: Ask questions, share ideas, or discuss before opening an issue
